### ISSUE TITLE
En tant que <utilisateur>, je veux pouvoir <filmer mon bulletin d'examen afin de l'envoyer au CPC> pour qu'il <me cree une facture>

### ISSUE THREAD

**Issue by maelfosso** [maelfosso/e-service#2]
## Tasks
- [ ] Prendre une photo de mon bulletin d'examen
- [ ] M'inscrire si je ne suis pas connecter
- [ ] Envoyer la photo au CPC
- [ ] Notifier le CPC de l'arrive d'une photo
## Definition of Done

L'user story sera dit **acheve** lorsqu'un utilisateur non connecte aura a la fin un compte et que le personnel du aura recu une notification du message de l'utilisateur

**Comment by malko1278** [comment]
vu...

Le 6 octobre 2016 à 10:26, Mael Elvis FOSSO notifications@github.com a
écrit :
