### ISSUE TITLE
En tant que <medecin/personnel CPC>, je veux pouvoir me connecter afin de creer des factures et effectuer d'autres operations 

### ISSUE THREAD

**Issue by maelfosso** [maelfosso/e-service#3]
## Tasks
- [ ] Build SignIn GUI
- [ ] Send data to the server
- [ ] Get server response
- [ ] Build Home GUI
