### ISSUE TITLE
En tant que <medecin/personnel CPC>, je veux pouvoir <creer une facture contenant un ou plusieurs examens parmi ceux disponible au CPC> afin de l'envoyer a un client

### ISSUE THREAD

**Issue by maelfosso** [maelfosso/e-service#5]
## Tasks
- [ ] Operation d'ajout et de suppression d'un examen de la facture
- [ ] Sauvegarde locale et distante de la facture
- [ ] Envoi de la facture au client
