### ISSUE TITLE
En tant qu'<client/medecin/CPC>, je veux pouvoir <consulter les messages echanges avec les medecins ou le CPC>

### ISSUE THREAD

**Issue by maelfosso** [maelfosso/e-service#6]
## Tasks

- [x] Interface Android minimal

- [ ] Interface Android - Joindre des fichiers 

- [ ] Communication avec le serveur

**Comment by malko1278** [comment]
Vu...

**Comment by malko1278** [comment]
Je lis tous le reste et je donne mon appréciation plus tard.

**Comment by malko1278** [comment]
Par disponible (#6 En tant qu'<client/medecin/CPC>, je veux pouvoir <consulter les messages echanges avec les medecins ou le CPC>) tu veux dire ceux qui sont fait aux CPC?
